CritterEmote_Locations = {
    "wants to explore all of Azeroth.",
    "would like to visit the Eastern Kingdoms.",
    "would like to go see the Dwarves at Dun Morogh.",
    "would like to see the vineyards in Elwynn Forest.",
    "would like to visit Eversong Woods.",
    "would like to visit Gilneas. Does wolfsbane really work with Worgens?",
    "would like to visit Tirisfal Glades.",
    "would like to visit Ghostlands",
    "wishes they could have seen the dam in Loch Modan before Darkwing destroyed it.",
    "would like to frolic in Silverpine Forest.",
    "would like to clear the bandits out of Westfall.",
    "would like to run along the riverside in Redridge Mountains.",
    "would like to see the spiders in Duskwood.",
    "would like to see the dinosaurs in Hillsbrad Foothills.",
    "would like to take a mudbath in the Wetlands.",
    "would like to visit the Alterac Mountains.",
    "would like to see the elementals in Arathi Highlands.",
    "would like to visit The Hinterlands.",
    "would like to see Stranglethorn.",
    "would like to become a zombie in Western Plaguelands.",
    "would like to bring the Light to the Eastern Plaguelands.",
    "would like to take a dust bath in the Badlands.",
    "would like to visit Searing Gorge.",
    "would like to visit Burning Steppes.",
    "never, ever wants to go to Deadwind Pass. It just sounds smelly.",
    "would not like to get stuck in a bog in the Swamp of Sorrows.",
    "would like to see the Dark Portal in The Blasted Lands.",
    "would like to see the tunnels in Khaz Modan.",
    "would like to visit the dungeons and raids in Blackrock Mountain.",
    "would like to visit the Opera in Karazhan.",
    "would like to earn gold on the Isle of Quel'Danas",
    "would not like to run into the Twighlight Counsel in Twilight Highlands.",
    "would like to win in Tol Barad and see Baradin Hold.",
    "would like to explore Azuremyst Isle. It sounds very blue.",
    "would like to visit the Trolls in Durotar.",
    "would like to see the Tauren in Mulgore.",
    "would like to visit the Night Elves in Teldrassil.",
    "wonders about all the red on Bloodmyst Isle.",
    "would like to frolic in Darkshore.",
    "thinks the Goblins have made Azshara a very odd place.",
    "would like to ride the tugboat in Northern Barrens.",
    "would like to explore Ashenvale.",
    "misses the Stonetalon Mountains from before the Shattering.",
    "Thinks Desolace is appropriately named.",
    "would like to explore Southern Barrens.",
    "would like to explore Dustwallow Marsh.",
    "would like to explore Feralas.",
    "remembers Thousand Needles before the Shattering and misses the races.",
    "would like to explore Tanaris.",
    "would like to explore Felwood.",
    "would like to see a dinosaur in Un'goro Crater.",
    "would like to take a mudbath in Un'goro Crater.",
    "would like to explore Winterspring.",
    "would like to see the sword hilt in Silithus.",
    "would like to explore Moonglade.",
    "would like to burn Mount Hyjal.",
    "would like to mine in Uldum.",
    "would like to explore Ahn'Qiraj.",
    "would like to see the beautiful Pandaria.",
    "wishes to see the Wandering Isle.",
    "wonders about Draenor and alternate universes.",
    "is afraid of the Broken Isles.",
    "is interested in seeing Outland.",
    "dreams about seeing the Dark Portal.",
    "wants to avoid Hellfire Peninsula.",
    "wants to avoid Zangarmarsh.",
    "loves Terokkar Forest.",
    "sings about Nagrand.",
    "thinks Blade's Edge Mountains are the coolest.",
    "would like to see if the stories about Netherstorm are true.",
    "asks if it really is always dark in Shadowmoon Valley.",
    "needs a coat to visit Borean Tundra.",
    "would like to see the Howling Fjord.",
    "wonders what Dragonblight is like.",
    "wonders what Grizzly Hills is like.",
    "would like to see the trolls of Zul'Drak.",
    "would like to see Sholazar Basin.",
    "would like to see the lightning in Storm Peaks.",
    "wonders how trees grow in Crystalsong Forest.",
    "would like to see Hrothgar's Landing.",
    "thinks Icecrown is a scary place.",
    "needs a coat to visit Wintergrasp.",
    "thinks Karazhan is a very tangled place but loves the Opera.",
    "wonders if they ever found the Lost Isles.",
    "would like to swim and breath underwater and see the cool things in Vashj'ir .",
    "would like to raid Icecrown Citadel.",
    "would like to raid The Firelands.",
    "would like to raid Dragon Soul.",
    "wants to be in the Celestial Tournament.",
    "would like to visit the Magical Menagerie.",
    "misses the Vale of Eternal Blossoms, remembering when it was beautiful and not scarred.",
    "never wants to see the world from Kun-Lai Summit.",
    "thinks Townlong Steppes is scary.",
    "wonders how the Wandering Isle wanders?",
    "would like to frolic in the Jade Forest.",
    "would like to go fishing in the Krasarang Wilds and meet Nat Pagle again.",
    "would like to burn the Dread Wastes to the ground.",
    "would like to dance in the thunder on the Isle of the Thunder King.",
    "thinks the dinosaurs of the Isle of Giants are impressive.",
    "wants to live forever on the Timeless Isle.",
    "wants to soar with the wind in the Valley of the Four Winds.",
    "would like to explore the Veiled Stair and buy something from the Black Market.",
    "thinks that the Tanaan Jungle has lots of cool things to see.",
    "would wear something warm when visiting Frostfire Ridge.",
    "wants to visit the elves of Suramar",
    "wants to hunt with Nat Pagel in Highmountain.",
    "wants to see the dragons of Stormheim.",
    "does not want to meet the Legion in Azsuna.",
    "wants to visit the druids in Val'Sharah.",
    "wonders about Thal'Dranath.",
    "wonders if Argus will ever be rid of the Legion.",
    "thinks that the Nightfallen in Suramar are glorified zombies.",
    "remembers when Zandalar rep was a grind before the Cataclysm.",
    "is amazed by Dazaralor.",
    "is a little frightened by Bwomsandi.",
    "wants to see the Volpera in Vol'dun.",
    "wishes Torga was still alive and wonders if there is a relation to the Shen-zin Su.",
    "wants to visit the Tortolla in Nazmir,",
    "wants to visit all the alleyways in Boralus.",
    "would like to fight with the pirates in Tiragarde Sound.",
    "wonders about the Drust of Drustvar.",
    "Thinks about the Shadowlands."
    
}