CritterEmote_Random
{
		"does a little dance.","does a little dance.",
		"is excited to see new places.",
		"looks around at all the people.",
		"sits on the floor.",
		"reads a very good book.",
		"takes some pictures.",
		"wants to know when it's dinner time.",
		"thinks you have very nice hair.",
		"charges into battle.",
		"looks cute.","looks cute.","looks cute.",
		"takes a long drink.",
		"has a cup of tea.","has a cup of tea.",
		"plants a garden.",
		"does a jig.",
		"goes off the deep end.",
		"sings.","sings.","sings.","sings.","sings.","sings.","sings.",
		"thinks all you need is love.",
		"blinks.","blinks.","blinks.","blinks.",
		"will tag along with you.",
		"loves you.","loves you.","loves you.",
		"adores you.","adores you.",
		"admires you.","admires you.",
		"winks.","winks.","winks.",
		"hides their loot.",
        "thinks the Lich King is scary.",
        "thinks Sargeras should go back to being an altruist.",
		"wants to go on an adventure.",
		"coos.",
		"giggles.",
		"wants to go adventuring.",
		"is tired.",
		"needs a nap.",
		"would like to take a break.",
		"wants to go mining.",
		"would like to try out skinning.",
        "would like to try out archaeology.",
        "would like to try out inscription",
		"wants to learn about troll history.",
		"loves archaeology.",
		"loves the Feast of Winter Veil.",
		"loves Brewfest.",
		"wants a drink.",
		"waves at everybody.",
		"puzzles over your outfit.",
		"plays with a small ball.",
		"thinks about the meaning of life.",
		"is interested in the number 23.",
		"squeaks.",
		"daydreams.",
		"would like to be fed.", "would like to be fed.",
		"dreams about being an adventurer.",
		"dreams about fighting the Lich King.",
		"dreams about fighting the Sha.",
		"dreams about fighting the Iron Horde.",
        "dreams about fighting the Legion",
        "dreams about fighting Sargeras",
        "dreams about fighting Darkwing",
		"dreams about being a fashion model.",
		"dreams about being a fire fighter.",
		"dreams about being a rock star.",
		"dreams about little pink fluffy clouds.",
        "dreams about ruling Azeroth.",
		"loves the color green.",
		"loves the color purple.",
		"stands up and waves.",
		"wants a glass of water.",
		"sits down comfortably.",
		"spits on the ground.",
		"curls up with a good book.",
		"needs a good therapist after the last adventure.",
		"looks around in awe.",
		"looks around in fear.",
		"looks around.",
		"looks around in confusion.",
		"is confused at the current situation.",
		"would like a cookie.",
		"would like some cake.",
		"would like some milk.",
		"would like some ice cream.",
		"understands that there are no bones in that ice cream.",
        "wants to go play at the auction house.",
		"wants to go play at the bank.",
		"wants to visit a transmogrifier for a change.",
		"can't stand waiting around.",
		"loves pumpkin pie.",
		"can't wait for the next fishing tournament.",
		"would love to go fishing.",
		"would love to do some cooking.",
		"dreams of far off lands.",
		"thinks we're all part of the matrix.", "thinks we're all part of the matrix.",
		"wants to fly a kite.",
		"eats some food.",
        "prepares a Savage Feast, for 1.",
		"prepares a Hearty Feast, for 1.",
		"prepares a feast for just themselves.",
		"wonders why we are here.",
        "likes space loopy not stringy.",
        "likes space stringy not loopy.",
		"wonders if you are real.",
		"cries.",
		"loves you!",
		"loves everybody!",
		"hates this place.",
		"loves this place.",
		"wants to bask in the glory of Onyxia.",
		"wants a pet biscuit.",
		"loves all the critters!",
		"climbs on your shoulders.",
		"chases a bug.",
		"paints.",
		"draws a line in the sand.",
		"wonders why Gronn was demoted from Dragonslayer to Captain Hook.",
		"wants to grow up to be a dragon.",
		"thinks, therefore is.",
		"ama il formaggio.",
		"wants to find true love.",
	}