CritterEmote_Songs_en= {
    "sings, \"I like tuna, I like chicken, I like liver, meow meow meow meow, meow meow meow meow.\"",
    "sings, \"It\'s not that easy being green, having to spend each day the color of the leaves, when I think it could be nicer being red, or yellow, or gold or something.\"",
    "sings, \"It\'s the hard-knock life for us! It\'s the hard-knock life for us! \'Steada treated, we get tricked! \'Steada kisses, we get kicked! It\'s the hard-knock life!\"",
    "sings [with a computer voice], \"When I look out there, it makes me glad I\'m not you. I\'ve got experiments to run. There is research to be done on the people who are still alive. And believe me I am still alive.\"",
    "sings, \"I don't care what you do, I wouldn't want to be like you.\"",
    "sings, \"Sunny day sweepin' the clouds away, on my way to where the air is sweet; can you tell me how to get, how to get to Sesame Street?\"",
    "sings, \"Do-do-do-do-do Dora! Do-do-do-do-do Dora! Dora Dora Dora the explorer! Boots, the super cool explora, Dora.\"",
    "sings, \"I\'ve got a lovely bunch of coconuts. There they are all standing in a row. Big ones, small ones, some as big as your head!\"",
    "sings, \"Jingle bell, jingle bell, jingle bell rock.  Jingle bells swing and jingle bells ring, snowing and blowing up bushels of fun, now the jingle hop has begun.\"",
    "sings, \"Imagine all the people living life in peace. You may say I\'m a dreamer but I\'m not the only one. I hope someday you\'ll join us and the world will be as one.\"",
    "sings, \"Cause I\'m the Boogie Man and if you aren\'t shakin\' then there\'s something very wrong. Cause this may be the last time now that you hear the boogie song. Oooh.\"",
    "sings, \"Get up, get on up, stay on the scene, like a sex machine.\"",
    "sings, \"I wanna be yours pretty baby, yours and yours alone. I\'m here to tell ya honey that I\'m bad to the bone. Bad to the bone. B-b-b-bad.\"",
    "sings, \"You just call on me brother when you need a hand. We all need somebody to lean on. I just might have a problem that you\'ll understand. We all need somebody to lean on.\"",
    "sings, \"Doo doo doo doo doo doo I\'m singing in the rain. Just singing in the rain. What a glorious feeling, I\'m happy again.\"",
    "sings, \"War, huh, yeah! What is it good for! Absolutely nothing! Say it again, you all.\"",
    "sings, \"Don\'t you want somebody to love. Don\'t you need somebody to love. Wouldn\'t you love somebody to love. You better find somebody to love, love, love.\"",
    "sings, \"But oh it\'s too hot, too hot lady. I gotta run for shelter, I gotta run for shade. It\'s too hot, too hot lady. Gotta cool this anger. What a mess we made.\"",
    "sings, \"But nothing ever happens and I wonder, I wonder how, I wonder why, yesterday you told me about the blue, blue sky and all that I can see is just another lemon tree.\"",
    "sings, \"Oohh ooo. Oohh ooo. What would Christmas be like without you here, singing at the bottom of the mistletoe waiting for you to come home.\"",
    "sings, \"Little darling, it's been a long cold lonely winter,Little darling, it feels like years since it's been here, Here comes the sun, here comes the sun,and I say it's all right.\"",
    "sings, \"I want your loving, And I want your revenge, You and me could write a bad romance.\"",
    "sings, \"Nights in white satin, never reaching the end. Letters I\'ve written, never meaning to send\"",
    "sings, \"99 dreams I have had, In every one a red balloon, It's all over and I'm standin' pretty, In this dust that was a city.\"",
    "sings, \"I like big butts and I can not lie, you other brothers can't deny, that when a girl walks in with an itty bitty waist and a round thing in your face, you get sprung!\"",
    "sings, \"I like\'em round and big, And when I\'m throwin\' a gig, I just can\'t help myself, I\'m actin like an animal.\"",
    "sings, \"Baby I\'m preying on you tonight, Hunt you down, eat you alive. Just like animals, animals, Like animals-mals.\"",
    "sings, \"I'm a Barbie girl, in a Barbie world. Life in plastic, it's fantastic!\"",
    "sings, \"Because the night belongs to lovers. Because the night belongs to lust. Because the night belongs to lovers. Because the night belongs to us.\"",
    "sings, \"How can we dance when our earth is turning, How do we sleep while our beds are burning.\"",
    "sings, \"Do you think you\'re better off alone? Talk to me...Ohhh, talk to me.\"",
    "sings, \"\'Cause it's a bittersweet symphony, this life. Trying to make ends meet.\"",
    "sings, \"I'm blue dabba dee-a dabba da da ba dee dabba da.\"",
    "sings, \"And I said, \"What about Breakfast at Tiffany\'s?\"\"",
    "sings, \"If you want it baby you\'ve got it. Just bust a move!\"",
    "sings, \"Come my lady. Come come my lady, you\'re my butterfly.\"",
    "sings, \"Butterfly kisses after bedtime prayer, Stickin\' little white flowers all up in her hair.\"",
    "sings, \"Here in my car, I feel safest of all, I can lock all my doors, It\'s the only way to live, In cars \"",
    "sings, \"Never gonna give you up, never gonna let you down, never gonna run around and desert you, never gonna make you cry, never gonna say goodbye, never gonna tell a lie and hurt you.\"",
    "sings, \"What is love? Baby don\'t hurt me, don\'t hurt me, no moooore.\"",
    "sings, \"Love bug, best kind of bug around (it’s a love bug, it’s a love bug), Love bug, best kind of bug—where the hugs come from.\"",
    "sings, \"Let it go, let it go! Turn away and slam the door. I don't care what they're going to say. Let the storm rage on. The cold never bothered me anyway.\"",
    "sings, \"Let me tell you how it will be, there\'s one for you and nineteen for me, cause I\'m the Taxman. \"",
    "sings, \"And in the end, the love you take is equal to the love you make.\"",
    "sings, \"Ob-la-di, Ob-la-da, life goes on.\"",
    "sings, \"Let it be, let it be. There will come an answer, let it be.\"",
    "sings, \"Life is very short and there's no time for fussing and fighting my friend. \"",
    "sings, \"Black, white, green, red, can I take my friend to bed? \"",
    "sings, \"I get by with a little help from my friends.\"",
    "sings, \"In my hour of darkness, she is standing right in front of me, speaking words of wisdom, let it be.\"",
    "sings, \"Blackbird singing in the dead of night, take these broken wings and learn to fly. All your life, you were only waiting for this moment to arrive, you were only waiting for this moment to be free.\"",
    "sings, \"I am the walrus, googoog a joob, googoog a joob.\"",
    "sings, \"I\'d like to be under the sea in an Octopus\'s garden in the shade.\"",
    "sings, \"Yesterday all my troubles seemed so far away. Now it looks as though they\'re here to stay. Oh, I believe in yesterday.\"",
    "sings, \"Honey pie, you are making me crazy. I'm in love, but I'm lazy. \"",
    "sings, \"Ah, look at all the lonely people.\"",
    "sings, \"Please, please me, oh yeah, like I please you.\"",
    "sings, \"I get high with a little help from my friends. Gonna try with a little help from my friends.\"",
    "sings, \"What would you do if I sang out of key?\"",
    "sings, \"It\'s getting better all the time, can\'t get no worse. \"",
    "sings, \"Here comes the sun, and it\'s alright.\"",
    "sings, \"The sun is up, the sky is blue, it\'s beautiful, and so are you.\"",
    "sings, \"He\'s a real nowhere man, sitting in his nowhere land, making all his nowhere plans for nobody.\"",
    "sings, \"I buried Paul.\"",
    "sings, \"I\'d love to turn you on.\"",
    "sings, \"We could have had it all, (You're gonna wish you never had met me). Rolling in the deep\"",
    "sings, \"And we'll never be royals.  It don't run in our blood, That kind of luxe just ain't for us.\"",
    "sings, \"We didn\'t start the fire. It was always burning, Since the world\'s been turning\"",
    "sings, \"Sweet dreams are made of this. Who am I to disagree? I travel the world, and the seven seas. Everybody's looking for something.\"",
    "sings, \"I just wanna use your love tonight. I don't wanna lose your love tonight\"",
    "sings, \"(Turn around, bright eyes), Every now and then I fall apart, And I need you now, tonight. And I need you more than ever\"",
    "sings, \"It\'s the eye of the tiger, It\'s the thrill of the fight, Risin\' up to the challenge of our rival",
    "sings, \"Every breath you take. Every move you make. Every bond you break. Every step you take. I\'ll be watching you.\"",
    "sings, \"Do you come from a land down under? Where women glow and men plunder? Can\'t you hear, can\'t you hear the thunder? You better run, you better take cover\"",
    "sings, \"It\'s gonna take a lot to drag me away from you. There\'s nothing that a hundred men or more could ever do. I bless the rains down in Africa. Gonna take some time to do the things we never had\"",
    "sings, \"Ah, push it - push it good. Ah, push it - push it real good. Ah, push it - push it good. Ah, push it - p-push it real good\"",
    "sings, \"Woah, we\'re half way there. Woah, livin\' on a prayer. Take my hand, we\'ll make it I swear. Woah, livin\' on a prayer\"",
    "sings, \"When you call my name it\'s like a little prayer. I\'m down on my knees, I wanna take you there\"",
    "sings, \"Oh, I wanna dance with somebody. I wanna feel the heat with somebody. Yeah, I wanna dance with somebody. With somebody who loves me\"",
    "sings, \"What rhymes with hug me?\"",
    "sings, \"Take me on (take on me). I'll be gone. In a day or two.\"",
    "sings, \"Puff the Magic Dragon lived by the Sea.\"",
    "sings, \"Ride, ride my seesaw, take my place, have my seat, it's for free.\"",
    "sings, \"Has anybody seen my baby? Has anybody seen her around?\"",
    "says, \"Whaddya want for nothin'? Rubber Bisquit? Ow, ow ow ow.\"",	
}