CritterEmote_Silly_en = {

    "wonders how the mail system works.",
    "thinks you should send your friends some mail.",
    "looks at all the lonely people.",
    "reads a comic.",
    "wonders what the secret sauce is made from.",
    "is concerned about the political state of affairs.",
    "plays catch.",
    "plays cards.",
    "plays backgammon.",
    "plays poker.",
    "plays jump rope.",
    "plays with a hula-hoop.",
    "plays 20 questions.",
    "plays solitaire.",
    "throws down a board to play Hearthstone.",
    "plays air guitar.", "plays air guitar.",
    "rocks out.",
    "gets down.",
    "parties!",
    "dreams of being a pirate.",
    "is a ninja.",
    "wonders what Mr. Bigglesworth is doing right now.",
    "waves their hands in the air like they just don't care.",
    "wants their noms.",
    "thinks that the night elf mohawk is the coolest.",
    "pretends to be a rocketship.  VROOOMMM",
    "thinks the Iron Horde are a bunch of silly billys.",
    "thinks pandas are funny looking.",
    "eats some hay, even though hay is for horses.",
    "picks a peck of pickled peppers",
    "twerks.",
    "shakes it like they just don't care.",
    "doesn't believe in ROUS.",  
    "says \"Say 'ello to my little friend!\"",
    "says \"You idiots! These are not them! You've captured their stunt doubles!\"",
    "says \"Gentlemen, you can't fight in here! This is the War Room.\"",
    "says \"No, now go away, or I shall taunt you a second time.\"",
    "says \"It's where I keep all my things. Get a lot of compliments on this. Plus, it's not a man-purse. It's called a satchel. Indiana Jones wears one.\"",
    "says \"Are you crying? There's no crying! There's no crying in the World of Warcraft!\"",
    "says \"Yeah, well. The Dude abides.\"",
    "says \"You brought the Pomeranian bowling?\"",
    "says \"I'll be back!\"",
    "says \"Keep it secret! Keep it safe!\"",
    "quotes \"Death need not concern us because when we exist death does not, and when death exists we do not.\"",
    "quotes \"Man is the measure of all things.\"",
    "quotes \"A categorical imperative would be one which represented an action as objectively necessary in itself, without reference to any other purpose.\"",
    "quotes \"Man is born free and is everywhere in chains.\"",
    "quotes \"The unexamined life is not worth living.\"",
    "quotes \"I think, therefore I am.\"",
    "quotes \"Cogito ergo sum.\"",
    "quotes \"Entities should not be multiplied unnecessarily.\"",
    "quotes \"Do unto others as you would have them do unto you.\"",
    "quotes \"All you need is love, Love. Love is all you need.\"",
    "quotes \"We don't go do stupid things when somebody yells, 'For the Horde'.\"",
    "quotes \"We don't go do stupid things when somebody yells, 'For the Alliance'.\"",
    "quotes \"Noble countrymen, evil is upon us. Darkness has befallen our shores. Rise and slay thy enemies… strike, strike so others shall live. The meek shall not fade into the night… live my brethren, live.\"",
    "quotes \"Do not go gentle into that long night.\"",
    "says \"It's been a hard day's night.\"",
    "plays Hearthstone.",
    "wants to join the Brawlers' Guild.",
    "thinks the Blingtrons are overcompensating.",
    "has a secret crush on Jaina Proudmoore.",
    "has a secret crush on Lor'themar Theron.",
    "has a secret crush on %t",
    "wants to be just like Thrall!",
    "can take Garrosh Hellscream in a fight.",
    "wonders what Valeera Sanguinar is doing now.",
    "thinks Pandas are silly.",
    "wants to harness time travel to re-write history as well!",
    "casts Armageddon",
    "laughs evilly while rubbing hands together.",
    "is the best pet ever!",
    "informs everybody that yellow #5 is poison!",
    "wants to make sure you are vaccinated!",
    "wants to make sure you are prepared.",
    "says \"You want the truth!  You can't handle the truth!\"",
    "says \"Wants to boldly go where no pet has gone before!\"",
    "says \"Ceci n'est une pipe\"",
    "says \"In bocca al lupo!\"",
    "says \"YOLO\"",
    "dreams of being a little pony.",
    "gets drunk.",
    "prepares a roast chicken.",
    "'s bag is bigger on the inside!",
    "says, \"is that a blue box?\"",
    "thinks it's all about that bass.",
    "poops.",
    "busts a move!",
    "grows a little garden",
    "says \"NI!\"",
    "thinks that sometimes a cigar is just a cigar.",
    "says \"go Red Sox!\"",
    "quotes \"Oh, that this too, too sullied flesh would melt\"",
    "quotes \"To be, or not to be, that is the question— Whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune...\"",
    "quotes \"All the world’s a stage, And all the men and women merely players\"",
    "quotes \"Once more unto the breach, dear friends, once more\"",
    "wonders why he wore the red shirt today.",
    "thinks, \"I'm a battle pet not a doctor!\"",
    "wants to protect the garrison.",
     "wonders how many more of these Abrogator stones do we need?",
     "thinks Archmage Khadgar should do his own dirty work.",
     "wants to join the Burning Legion",
     "wants to go fight in the Highmaul Arena.",
     "loves Deathwing.",
     "wants to tank.",
     "thinks podlings are mean.",
     "justifies existence by deeps score.",
     "takes a deep breath!",
     "shouts \"Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn.\"",
     "whispers \"They are coming for you...\"",
     "whispers \"Kill them all... before they kill you...\"",
     "whispers \"Trust is your weakness...\"",
     "whispers \"Hope is an illusion...\"",
     "whispers \"All that you know will fade...\"",
     "whispers \"You are a pawn of forces unseen...\"",
     "knows Yogg-Saron will destroy the world.",
     "whispers \"You will betray your friends.\"",
     "digs C'Thun's eye.",
     "sees all!",
     "rides a pale horse.",
     "throws a dance party!",
}