CritterEmote_Strings = {
    ["WELCOME_MESSAGE"] = "Benvenuto a CritterEmote",
    ["WELCOME_INFO"] = "Digita <cmd>/ce help</cmd> per un elenco di comandi.",
    ["WELCOME_CE"] = "Saluti, amante delle creature!",
    ["WELCOME_ACTIVE"] = "Critter Emote è attualmente: ",
    ["WELCOME_VERSION"] = "La versione di Critter Emote è: " .. CritterEmote_version,
    ["HELP_GENERAL"] = "<cmd>/ce</cmd> permette alla tua creatura di emettere ciò che vuoi.",
    ["HELP_1"] = "<cmd>/ce</cmd> - fai fare un'emote casuale alla tua creatura.",
    ["HELP_2"] = "<cmd>/ce <messaggio></cmd> - fai fare un'emote del tuo <messaggio> alla tua creatura.",
    ["HELP_3"] = "<cmd>/ce [opzioni]</cmd> - esegui l'opzione richiesta:",
    ["HELP_4"] = "[opzioni] = ",
    ["HELP_5"] = "info   : visualizza le informazioni di Critter Emote.",
    ["HELP_6"] = "help   : visualizza questo aiuto.",
    ["HELP_7"] = "off    : disattiva le emote.",
    ["HELP_8"] = "on     : attiva le emote.",
    ["HELP_9"] = "random_off : disattiva tutte le emote casuali.",
    ["HELP_10"] = "random_on : attiva tutte le emote casuali.",
    ["HELP_11"] = "options: visualizza le opzioni correnti.",
    ["HELP_12"] = "silly  : Attiva/Disattiva le emote sciocche.",
    ["HELP_13"] = "special  : Attiva/Disattiva le emote speciali.",
    ["HELP_14"] = "locations  : Attiva/Disattiva le emote di posizione.",
    ["HELP_15"] = "songs  : Attiva/Disattiva le emote di canzoni.",
    ["HELP_16"] = "PVP  : Attiva/Disattiva le emote PVP.",
    ["HELP_17"] = "general  : Attiva/Disattiva le emote generali.",
    ["HELP_18"] = "debug  : Attiva la modalità debug.",
    ["HELP_19"] = "debug off  : Disattiva la modalità debug.",
    ["SAVE_CUSTOM_CHAT"] = "Vuoi salvare questo messaggio di chat personalizzato?",
    ["MESSAGE_SAVED"] = "Messaggio salvato.",
    ["NO_PET_SUMMONED"] = "Nessun animale domestico è attualmente evocato.",
    ["NO_ACTIVE_CRITTER"] = "Non hai nessun animale attivo.",
    ["OPTIONS"] = "Opzioni",
}

