CritterEmote_Strings = {
    ["WELCOME_MESSAGE"] = "Bienvenue à CritterEmote",
    ["WELCOME_INFO"] = "Tapez <cmd>/ce help</cmd> pour une liste des commandes.",
    ["WELCOME_CE"] = "Salutations, amateur de créatures!",
    ["WELCOME_ACTIVE"] = "Critter Emote est actuellement: ",
    ["WELCOME_VERSION"] = "La version de Critter Emote est: " .. CritterEmote_version,
    ["HELP_GENERAL"] = "<cmd>/ce</cmd> permet à votre créature d'emoter ce que vous voulez.",
    ["HELP_1"] = "<cmd>/ce</cmd> - faites faire un emote aléatoire à votre créature.",
    ["HELP_2"] = "<cmd>/ce <message></cmd> - faites faire un emote de votre <message> à votre créature.",
    ["HELP_3"] = "<cmd>/ce [options]</cmd> - exécute l'option demandée:",
    ["HELP_4"] = "[options] = ",
    ["HELP_5"] = "info   : affiche les informations de Critter Emote.",
    ["HELP_6"] = "help   : affiche cette aide.",
    ["HELP_7"] = "off    : désactive les emotes.",
    ["HELP_8"] = "on     : active les emotes.",
    ["HELP_9"] = "random_off : désactive tous les emotes aléatoires.",
    ["HELP_10"] = "random_on : active tous les emotes aléatoires.",
    ["HELP_11"] = "options: affiche les options actuelles.",
    ["HELP_12"] = "silly  : Active/Désactive les emotes stupides.",
    ["HELP_13"] = "special  : Active/Désactive les emotes spéciaux.",
    ["HELP_14"] = "locations  : Active/Désactive les emotes de localisation.",
    ["HELP_15"] = "songs  : Active/Désactive les emotes de chansons.",
    ["HELP_16"] = "PVP  : Active/Désactive les emotes PVP.",
    ["HELP_17"] = "general  : Active/Désactive les emotes généraux.",
    ["HELP_18"] = "debug  : Active le mode débogage.",
    ["HELP_19"] = "debug off  : Désactive le mode débogage.",
    ["SAVE_CUSTOM_CHAT"] = "Voulez-vous enregistrer ce message de chat personnalisé?",
    ["MESSAGE_SAVED"] = "Message enregistré.",
    ["NO_PET_SUMMONED"] = "Aucun familier n'est invoqué actuellement.",
    ["NO_ACTIVE_CRITTER"] = "Vous n'avez pas de familier actif.",
    ["OPTIONS"] = "Options",
    
}

