CritterEmote_Strings = {
    ["WELCOME_MESSAGE"] = "Welcome to CritterEmote",
    ["WELCOME_INFO"] = "Type <cmd>/ce help</cmd> for a list of commands.",
    ["WELCOME_CE"] = "Greetings critter lover!",
    ["WELCOME_ACTIVE"] = "Critter Emote is currently: ",
    ["WELCOME_VERSION"] = "Critter Emote version is: " .. CritterEmote_version,
    ["HELP_GENERAL"] = "<cmd>/ce</cmd> has critter emote whatever you like.",
    ["HELP_1"] = "<cmd>/ce</cmd> - have your critter perform a random emote.",
    ["HELP_2"] = "<cmd>/ce <message></cmd> - have your critter emote your <message>.",
    ["HELP_3"] = "<cmd>/ce [options]</cmd> - perform the requested option:",
    ["HELP_4"] = "[options] = ",
    ["HELP_5"] = "info   : displays Critter Emote information.",
    ["HELP_6"] = "help   : displays this help.",
    ["HELP_7"] = "off    : turns the emotes off.",
    ["HELP_8"] = "on     : turns the emotes on.",
    ["HELP_9"] = "random_off : turns all random emotes off.",
    ["HELP_10"] = "random_on : turns all random emotes on.",
    ["HELP_11"] = "options: Displays current options.",
    ["HELP_12"] = "silly  : Toggles silly emotes.",
    ["HELP_13"] = "special  : Toggles special emotes.",
    ["HELP_14"] = "locations  : Toggles location emotes.",
    ["HELP_15"] = "songs  : Toggles song emotes.",
    ["HELP_16"] = "PVP  : Toggles PVP emotes.",
    ["HELP_17"] = "general  : Toggles general emotes",
    ["HELP_18"] = "debug  : Turns debug on.",
    ["HELP_19"] = "debug off  : Turns debug off.",
    ["SAVE_CUSTOM_CHAT"] = "Do you want to save this custom chat message?",
    ["MESSAGE_SAVED"] = "Message saved.",
    ["NO_PET_SUMMONED"] = "No pet is currently summoned.",
    ["NO_ACTIVE_CRITTER"] = "You do not have an active critter out.",
    ["OPTIONS"] = "Options",
}

